import { Router } from "express";
import { z } from "zod";
import { supabase } from "../lib/supabase.js";

const router = Router();

const linkSchema = z.object({ code: z.string().min(1) });

/**
 * Binds telegram_user_id to the currently-authenticated (real, web-signed-up) Supabase user.
 * The code was generated by kira-bot's /start against a "shadow" profile (see
 * routes/telegram.ts), which owns the telegram_user_id until this transfers it. telegram_user_id
 * is unique on kira_profiles, so the shadow profile's value must be cleared before the real
 * profile can take it.
 */
router.post("/telegram-link", async (req, res) => {
  const parsed = linkSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid payload", details: parsed.error.flatten() });
    return;
  }
  const { code } = parsed.data;

  const { data: linkCode, error: codeError } = await supabase
    .from("kira_link_codes")
    .select("code, user_id, expires_at, used")
    .eq("code", code)
    .maybeSingle();

  if (codeError) {
    console.error("[kira-api:auth] link code lookup failed:", codeError.message);
    res.status(500).json({ error: "Internal server error" });
    return;
  }
  if (!linkCode) {
    res.status(404).json({ error: "Invalid link code" });
    return;
  }
  if (linkCode.used) {
    res.status(410).json({ error: "Link code already used" });
    return;
  }
  if (new Date(linkCode.expires_at).getTime() < Date.now()) {
    res.status(410).json({ error: "Link code expired" });
    return;
  }

  if (linkCode.user_id === req.user!.id) {
    // Already the same account, nothing to transfer.
    await supabase.from("kira_link_codes").update({ used: true }).eq("code", code);
    res.json({ linked: true });
    return;
  }

  const { data: shadowProfile, error: shadowError } = await supabase
    .from("kira_profiles")
    .select("telegram_user_id, telegram_username")
    .eq("id", linkCode.user_id)
    .maybeSingle();

  if (shadowError || !shadowProfile?.telegram_user_id) {
    console.error("[kira-api:auth] shadow profile lookup failed:", shadowError?.message);
    res.status(404).json({ error: "Link code's Telegram account not found" });
    return;
  }

  const { error: clearError } = await supabase
    .from("kira_profiles")
    .update({ telegram_user_id: null, telegram_username: null })
    .eq("id", linkCode.user_id);

  if (clearError) {
    console.error("[kira-api:auth] clearing shadow profile failed:", clearError.message);
    res.status(500).json({ error: "Internal server error" });
    return;
  }

  const { error: assignError } = await supabase
    .from("kira_profiles")
    .update({
      telegram_user_id: shadowProfile.telegram_user_id,
      telegram_username: shadowProfile.telegram_username,
    })
    .eq("id", req.user!.id);

  if (assignError) {
    console.error("[kira-api:auth] assigning telegram link failed:", assignError.message);
    // Best-effort rollback so the shadow profile isn't left orphaned of its own telegram id.
    await supabase
      .from("kira_profiles")
      .update({
        telegram_user_id: shadowProfile.telegram_user_id,
        telegram_username: shadowProfile.telegram_username,
      })
      .eq("id", linkCode.user_id);
    res.status(500).json({ error: "Internal server error" });
    return;
  }

  await supabase.from("kira_link_codes").update({ used: true }).eq("code", code);

  res.json({ linked: true });
});

export default router;
